version: '3'

services:
  app:
    image: auth:nightly
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/node/app
    command: /bin/ash -c "npm install && npm start"
    environment:
      API_KEY: some-random-ultra-secret-key
    ports:
      - 8080:8080
