apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: enJw # zrp
  mongo-root-password: enJwMTIzNA== # zrp1234
  mongo-url: bW9uZ29kYjovL3pycDp6cnAxMjM0QG1vbmdvZGIuZGVmYXVsdDoyNzAxNy9zYW1wbGU/YXV0aFNvdXJjZT1hZG1pbg== # mongodb://zrp:zrp1234@mongodb.default:27017/sample?authSource=admin
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  api-key: c29tZS1yYW5kb20tdWx0cmEtc2VjcmV0LWtleQ== # some-random-ultra-secret-key
